/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLOSE = 5;
  /** RegularExpression Id. */
  int OPEN = 6;
  /** RegularExpression Id. */
  int OPENSQ = 7;
  /** RegularExpression Id. */
  int CLOSESQ = 8;
  /** RegularExpression Id. */
  int QUOTE = 9;
  /** RegularExpression Id. */
  int MATHOP = 10;
  /** RegularExpression Id. */
  int LOGICOP = 11;
  /** RegularExpression Id. */
  int COMPAREOP = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int SPECIAL = 15;
  /** RegularExpression Id. */
  int DEF = 16;
  /** RegularExpression Id. */
  int DEFN = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int ATOM = 20;
  /** RegularExpression Id. */
  int PRINT = 21;
  /** RegularExpression Id. */
  int LOOP = 22;
  /** RegularExpression Id. */
  int SWAP = 23;
  /** RegularExpression Id. */
  int WHEN = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int RECUR = 26;
  /** RegularExpression Id. */
  int CASE = 27;
  /** RegularExpression Id. */
  int READ = 28;
  /** RegularExpression Id. */
  int REPEAT = 29;
  /** RegularExpression Id. */
  int BOOL = 30;
  /** RegularExpression Id. */
  int VAR = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int STR = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int ENDPROGRAM = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\")\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "<MATHOP>",
    "<LOGICOP>",
    "<COMPAREOP>",
    "<CHAR>",
    "<DIGIT>",
    "<SPECIAL>",
    "\"def\"",
    "\"defn\"",
    "\"if\"",
    "\"while\"",
    "\"atom\"",
    "\"println\"",
    "\"loop\"",
    "\"swap!\"",
    "\"when\"",
    "\"do\"",
    "\"recur\"",
    "\"case\"",
    "\"read-line\"",
    "\"repeat\"",
    "<BOOL>",
    "<VAR>",
    "<INT>",
    "<STR>",
    "\",\"",
    "\"##\"",
    "\"{\"",
    "\"}\"",
  };

}
